# Generated by Django 5.2.7 on 2025-10-22 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_DEPARTMENT',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DB_FACULTY',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.EmailField(max_length=254, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='api.db_department')),
            ],
        ),
        migrations.AddField(
            model_name='db_department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='api.db_faculty'),
        ),
        migrations.CreateModel(
            name='DB_COURSE',
            fields=[
                ('course_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.db_department')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='api.db_faculty')),
            ],
        ),
        migrations.CreateModel(
            name='DB_STUDENT',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_mail', models.EmailField(max_length=254, unique=True)),
                ('student_age', models.PositiveIntegerField()),
                ('student_courses', models.ManyToManyField(related_name='students', to='api.db_course')),
                ('student_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.db_department')),
            ],
        ),
    ]
